- name: backend configuration
  hosts: backend
  become: yes
  tasks:
  - name: install nodejs
    ansible.builtin.command: "dnf module disable nodejs -y"

  - name: enable nodejs
    ansible.builtin.command: "dnf module enable nodejs:20 -y"  

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: latest

  - name: useradd
    ansible.builtin.user:
      name: expense   

  - name: app
    ansible.builtin.file:
      path: /app
      state: directory
  - name: unarchieve
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /app
      remote_src: yes    



 