- name: db configuration
  hosts: db
  become: yes 
  tasks:
  - name: db
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
