- name: db configuration 
  hosts: db
  become: yes
  vars:
    login_password: ExpenseApp@1
    login_host: db.narendra.shop
  tasks:
  - name: install mysql-server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: systemctl enable mysqld   
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes 

  - name: mysql info
    community.mysql.mysql_info:
      login_user: root
      login_password: {{mysql_root_password}}
      login_host: {{login_host}}
      filter: version
    ignore_errors:  true
    register: mysql_connection_output

       


