- name: db configuration
  hosts: db
  become: yes 
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: db.narendra.shop

  tasks:
  - name: db
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
      
  - name: install python mysql depenencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9       

  - name: checking password set or not
    community.mysql.mysql_info:
      login_user: root
      login_host: "{{login_host}}"
      login_password: "{{mysql_root_password}}"
      filter: version    
    ignore_errors: yes 
    register: mysql_connection_output





