- name: configure frontnend
  hosts: frontend
  become: yes
  tasks:
  - name: dnf install nginx -y 
    ansible.builtin.dnf:
      name: nginx 
      state: installed

  - name: enable
    ansible.builtin.service:
      name: nginx 
      state: started
      enabled: yes

  - name: html removal
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: html addition
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: unarchieve
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html 




